#!/bin/bash -e

echo "   ___                  __                  _     _ _             ";
echo "  / _ \_ __ ___        /__\ ___  __ _ _   _(_)___(_) |_ ___  ___  ";
echo " / /_)/ '__/ _ \_____ / \/// _ \/ _\` | | | | / __| | __/ _ \/ __| ";
echo "/ ___/| | |  __/_____/ _  \  __/ (_| | |_| | \__ \ | ||  __/\__ \ ";
echo "\/    |_|  \___|     \/ \_/\___|\__, |\__,_|_|___/_|\__\___||___/ ";
echo "                                   |_|                            ";

RESET='\033[0m'
COLOR='\033[1;32m'

msg() {
  echo -e "${COLOR}$(date): $1${RESET}"
}

msg "Block Periodic Updates"
sudo sed -i.bak 's=APT::Periodic::Update-Package-Lists "1";=APT::Periodic::Update-Package-Lists "0";=g' /etc/apt/apt.conf.d/10periodic
sudo sed -i.bak 's=APT::Periodic::Update-Package-Lists "1";=APT::Periodic::Update-Package-Lists "0";=g' /etc/apt/apt.conf.d/20auto-upgrades
sudo sed -i.bak 's=APT::Periodic::Unattended-Upgrade "1";=APT::Periodic::Unattended-Upgrade "0";=g' /etc/apt/apt.conf.d/20auto-upgrades

msg "Upgrading packages once"
sudo apt update
sudo apt remove lxd lxd-client -y
sudo apt upgrade -y

msg "Installing Generic Tools and Applying some fixes"
sudo apt install -yq --no-install-recommends \
                         openssh-server \
                         avahi-daemon \
                         avahi-utils \
                         wget \
                         bzip2 \
                         ca-certificates \
                         sudo \
                         locales \
                         fonts-liberation \
                         curl \
                         nano \
                         build-essential \
                         apt-file \
                         pkg-config \
                         gfortran
                         

msg "Updating cmake"
cmake_filename=cmake-3.11.3-Linux-x86_64.tar.gz
cmake_folder=cmake-3.11.3-Linux-x86_64
cp /utils/cmake/$cmake_filename $HOME/$cmake_filename
tar -xf $HOME/$cmake_filename -C $HOME
cd $HOME/$cmake_folder
sudo cp -R ./bin /usr/
sudo cp -R ./share /usr/
sudo cp -R ./doc /usr/share/
sudo cp -R ./man /usr/share/
cd .. && rm -rf $HOME/$cmake_folder

msg "Building and Installing Git (2.19.0)"
sudo apt install -y libz-dev gettext libcurl4-openssl-dev
cd $HOME
wget https://mirrors.edge.kernel.org/pub/software/scm/git/git-2.19.0.tar.xz
tar -xf git-2.19.0.tar.xz 
cd git-2.19.0
./configure
make -j4
sudo make install

msg "Updating gcc and g++"
sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
sudo apt update
sudo apt install -y gcc-6 gcc-7 gcc-8 g++-6 g++-7 g++-8
sudo ln -s -f /usr/bin/gcc-7 /usr/bin/gcc
sudo ln -s -f /usr/bin/g++-7 /usr/bin/g++

sudo apt autoremove -y
#sudo apt-file update
sudo sed -i.bak "s=rlimit-nproc\=3=#rlimit-nproc\=3=g" /etc/avahi/avahi-daemon.conf

msg "Fixing container locales"
sudo locale-gen en_US.UTF-8
#sudo apt-get install -yq --no-install-recommends language-pack-en