#!/bin/bash -e

echo "   __                                 _       _    ";
echo "   \ \  __ ___   ____ _ ___  ___ _ __(_)_ __ | |_  ";
echo "    \ \/ _\` \ \ / / _\` / __|/ __| '__| | '_ \| __| ";
echo " /\_/ / (_| |\ V / (_| \__ \ (__| |  | | |_) | |_  ";
echo " \___/ \__,_| \_/ \__,_|___/\___|_|  |_| .__/ \__| ";
echo "                                       |_|         ";

RESET='\033[0m'
COLOR='\033[1;32m'

msg() {
  echo -e "${COLOR}$(date): $1${RESET}"
}

cd $HOME
if [[ "$#" -gt 0 ]];then
  PYTHON_VERSION="$1"
  
  export PYENV_ROOT=$HOME/.pyenv
  export PATH=$PYENV_ROOT/bin:$PATH
  eval "$(pyenv init -)"
  
  pyenv local $PYTHON_VERSION

  export PATH=$HOME/.local/bin:$PATH
  export PYTHONPATH=/home/ubuntu/.pyenv/versions/$PYTHON_VERSION/lib/python3.6/site-packages
  #export PYTHONPATH=$HOME/.local/lib/python3.6/site-packages

  export PYTHON_BIN_PATH=/home/ubuntu/.pyenv/shims/python
  #export PYTHON_BIN_PATH=/usr/bin/python3

  export PYTHON_LIB_PATH=/home/ubuntu/.pyenv/versions/$PYTHON_VERSION/lib/python3.6/site-packages
  #export PYTHON_LIB_PATH=$HOME/.local/lib/python3.6/site-packages

  #msg "Installing Pre-requisites for docs"
  #sudo apt-get -qy install pandoc texlive-xetex
fi

#cd $HOME
#export PATH=$HOME/.local/bin:$PATH
#export PYTHONPATH=$HOME/.local/lib/python3.6/site-packages
#export PYTHON_BIN_PATH=/usr/bin/python3
#export PYTHON_LIB_PATH=$HOME/.local/lib/python3.6/site-packages

msg "Installing Javascript kernel for Jupyter"
npm install -g ijavascript

ijsinstall