#!/bin/bash -e

echo "   __        _ _        ";
echo "   \ \ _   _| (_) __ _  ";
echo "    \ \ | | | | |/ _\` | ";
echo " /\_/ / |_| | | | (_| | ";
echo " \___/ \__,_|_|_|\__,_| ";
echo "                        ";

RESET='\033[0m'
COLOR='\033[1;32m'

msg() {
  echo -e "${COLOR}$(date): $1${RESET}"
}

cd ${HOME}
if [[ "$#" -gt 0 ]];then
  
  PYTHON_VERSION="$1"
  
  if [[ "$#" -gt 1 ]];then
    PYTHON_ENVIRONMENT="$2"
  fi
  
fi

#[DEPRECATED]
enable_pyenv()
{
  export PYENV_ROOT=${HOME}/.pyenv
  export PATH=${PYENV_ROOT}/bin:${PATH}
  eval "$(pyenv init -)"

  pyenv local ${PYTHON_VERSION}

  export PATH=${HOME}/.local/bin:${PATH}

  export PYTHONPATH=/home/ubuntu/.pyenv/versions/${PYTHON_VERSION}/lib/python3.6/site-packages
  #export PYTHONPATH=$HOME/.local/lib/python3.6/site-packages

  export PYTHON_BIN_PATH=/home/ubuntu/.pyenv/shims/python
  #export PYTHON_BIN_PATH=/usr/bin/python3

  export PYTHON_LIB_PATH=/home/ubuntu/.pyenv/versions/${PYTHON_VERSION}/lib/python3.6/site-packages
  #export PYTHON_LIB_PATH=$HOME/.local/lib/python3.6/site-packages

  #msg "Installing Pre-requisites for docs"
  #sudo apt-get -qqy install pandoc texlive-xetex
}

enable_miniconda()
{
  export PATH="${HOME}/.local/bin:${PATH}"
  export PATH="${HOME}/anaconda/bin:${PATH}"
  source activate projects
  #source activate projects
}

if [[ ${PYTHON_ENVIRONMENT} == "pyenv" ]];then
    enable_pyenv;
elif [[ ${PYTHON_ENVIRONMENT} == "miniconda" ]];then
    enable_miniconda;
fi

msg "Installing Julia"
major=1
minor=0
patch=0
julia_version=${major}.${minor}
julia_filename=julia-${julia_version}.${patch}-linux-x86_64.tar.gz

mkdir -p ${HOME}/julia
cd ${HOME}

if [[ ! -e "${HOME}/${julia_filename}" ]];
then
    wget https://julialang-s3.julialang.org/bin/linux/x64/${julia_version}/${julia_filename} -O ${HOME}/${julia_filename}
    tar -xf ${HOME}/${julia_filename} -C ${HOME}/julia/
    rm ${HOME}/${julia_filename}
    chown ubuntu:ubuntu ${HOME}/julia/ -R
    julia_folder=$(ls ${HOME}/julia/)
    sudo ln -s ${HOME}/julia/${julia_folder}/bin/julia /usr/bin/julia
fi

#mv /home/ubuntu/julia/${julia_folder} /home/ubuntu/julia/${julia_version}
msg "Installing Julia kernel for jupyter (IJulia)"
julia -e "using Pkg;Pkg.add(\"IJulia\")"