#!/bin/bash -e

echo "     __          _       __        ";
echo "  /\ \ \___   __| | ___  \ \  ___  ";
echo " /  \/ / _ \ / _\` |/ _ \  \ \/ __| ";
echo "/ /\  / (_) | (_| |  __/\_/ /\__ \ ";
echo "\_\ \/ \___/ \__,_|\___\___/ |___/ ";
echo "                                   ";

export FROM_SOURCE='yes'

RESET='\033[0m'
COLOR='\033[1;32m'

msg() {
  echo -e "${COLOR}$(date): $1${RESET}"
}

install_binary(){

  msg "Installing NodeJs Binary (8.xx)"
  #only works for python3.5/python2.7 pre-installed
  # [DEPRECATED until resolution of the community]
  # This way creates a problem that the packages folder will need previleges (sudo)
  #curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
  #sudo apt update
  #sudo apt install -y --no-install-recommends nodejs
  #sudo npm i -g npm
  #sudo chown -R ${USER}:$(id -gn ${USER}) ${HOME}/.config

  wget -qO- https://deb.nodesource.com/setup_8.x | sudo -E bash -
  sudo apt update  -qqy
  sudo apt install -qqy --no-install-recommends nodejs
  sudo npm i -g npm
  sudo chown -R ${USER}:$(id -gn ${USER}) ${HOME}/.config

}

install_from_source(){

  msg "Building NodeJs Sources (8.xx)"
  sudo apt update -qqy
  sudo apt install python-minimal -qqy
  node_version=v8.12.0
  nodejs_filename=node-${node_version}.tar.gz

  cd ${HOME}
  if [[ ! -e "${HOME}/${nodejs_filename}" ]];
  then
    wget https://nodejs.org/dist/${node_version}/${nodejs_filename}
    tar -xf ${nodejs_filename}
    rm ${HOME}/${nodejs_filename}
  fi

  cd ${HOME}/node-v8.11.3
  ./configure --prefix=${HOME}/.local
  make -j"$(nproc)"
  make install
  ln -s ${HOME}/.local/lib/node_modules ${HOME}/.node_modules
  export PATH=${HOME}/.local/bin:${PATH}
}

if [[ "$#" -gt 0 ]];then
  FROM_SOURCE="$1"
fi


if [[ ${FROM_SOURCE} == 'yes' ]];then
  install_from_source;
else
  install_binary;
fi

