#!/bin/bash -e

echo "   ___     _                   ";
echo "  /___\___| |_ __ ___   _____  ";
echo " //  // __| __/ _\` \ \ / / _ \ ";
echo "/ \_// (__| || (_| |\ V /  __/ ";
echo "\___/ \___|\__\__,_| \_/ \___| ";
echo "                               ";

RESET='\033[0m'
COLOR='\033[1;32m'
msg() {
    echo -e "${COLOR}$(date): $1${RESET}"
}

cd ${HOME}
if [[ "$#" -gt 0 ]];then
  
  PYTHON_VERSION="$1"
  
  if [[ "$#" -gt 1 ]];then
    PYTHON_ENVIRONMENT="$2"
  fi
  
fi

#[DEPRECATED]
enable_pyenv()
{
  export PYENV_ROOT=${HOME}/.pyenv
  export PATH=${PYENV_ROOT}/bin:${PATH}
  eval "$(pyenv init -)"

  pyenv local ${PYTHON_VERSION}

  export PATH=${HOME}/.local/bin:${PATH}
  export PYTHONPATH=/home/ubuntu/.pyenv/versions/${PYTHON_VERSION}/lib/python3.6/site-packages
  #export PYTHONPATH=$HOME/.local/lib/python3.6/site-packages

  export PYTHON_BIN_PATH=/home/ubuntu/.pyenv/shims/python
  #export PYTHON_BIN_PATH=/usr/bin/python3

  export PYTHON_LIB_PATH=/home/ubuntu/.pyenv/versions/${PYTHON_VERSION}/lib/python3.6/site-packages
  #export PYTHON_LIB_PATH=${HOME}/.local/lib/python3.6/site-packages

  #msg "Installing Pre-requisites for docs"
  #sudo apt-get -qy install pandoc texlive-xetex
}

enable_miniconda()
{
  export PATH="${HOME}/.local/bin:${PATH}"
  export PATH="${HOME}/anaconda/bin:${PATH}"
  source activate projects
  #source activate projects
}

if [[ ${PYTHON_ENVIRONMENT} == "pyenv" ]];then
    enable_pyenv;
elif [[ ${PYTHON_ENVIRONMENT} == "miniconda" ]];then
    enable_miniconda;
fi

msg "Installing Octave"
sudo apt update  -qq
sudo apt install -qqy --no-install-recommends \
                      octave

msg "Installing Octave kernel for Jupyter"
pip install --user -U metakernel octave_kernel