#!/bin/bash -e

echo "   ___       _   _                 _____  ";
echo "  / _ \_   _| |_| |__   ___  _ __ |___ /  ";
echo " / /_)/ | | | __| '_ \ / _ \| '_ \  |_ \  ";
echo "/ ___/| |_| | |_| | | | (_) | | | |___) | ";
echo "\/     \__, |\__|_| |_|\___/|_| |_|____/  ";
echo "       |___/                              ";

RESET='\033[0m'
COLOR='\033[1;32m'

export PYTHON_VERSION=3.5.2

msg() {
  echo -e "${COLOR}$(date): $1${RESET}"
}

install_pyenv() {

    sudo apt install -qqy  python3-pip \
                           openssl \
                           libbz2-dev \
                           libreadline-dev \
                           libssl-dev \
                           libsqlite3-dev

    cd ${HOME}
    git clone https://github.com/pyenv/pyenv.git ${HOME}/.pyenv

    export PYENV_ROOT=${HOME}/.pyenv
    export PATH=${PYENV_ROOT}/bin:$PATH
    
    echo "export PYENV_ROOT=${HOME}/.pyenv" | tee -a ${HOME}/.bashrc
    echo 'export PATH=$PYENV_ROOT/bin:$PATH' | tee -a ${HOME}/.bashrc

    eval "$(pyenv init -)"
    echo 'eval "$(pyenv init -)"' | tee -a ${HOME}/.bashrc
    echo "export PYENV_VERSION=${PYTHON_VERSION}" |  tee -a ${HOME}/.bashrc
    echo "export PYTHONPATH=/home/ubuntu/.pyenv/versions/${PYTHON_VERSION}/lib/python3.6/site-packages" | tee -a ${HOME}/.bashrc
    echo "export PYTHON_BIN_PATH=/home/ubuntu/.pyenv/shims/python" | tee -a ${HOME}/.bashrc
    echo "export PYTHON_LIB_PATH=/home/ubuntu/.pyenv/versions/${PYTHON_VERSION}/lib/python3.6/site-packages" | tee -a ${HOME}/.bashrc

    pyenv install ${PYTHON_VERSION}
    pyenv local ${PYTHON_VERSION}
    pip install -U pip
    #--user

    sudo apt remove -qqy python3-pip

    #pip --version: pip 18.1 from /home/ubuntu/.pyenv/versions/3.6.6/lib/python3.6/site-packages/pip (python 3.6)
    echo $(pip --version | cut -d" " -f4  )

    #python --version: Python 3.6.6
    echo $(python --version | cut -d" " -f2)
}

#sudo apt update -qq
#sudo apt install -yq \
#            python3 \
#            python3-dev \
#            python3-tk \
#            libpython3-dev \
#            libpython3-stdlib \
#            python3-setuptools \
#            python3-numpy \
#            python3-pip

if [[ "$#" -gt 0 ]];then
    PYTHON_VERSION="$1"
fi

install_pyenv