#!/bin/bash -e

echo "   ___       _   _                 _____  ";
echo "  / _ \_   _| |_| |__   ___  _ __ |___ /  ";
echo " / /_)/ | | | __| '_ \ / _ \| '_ \  |_ \  ";
echo "/ ___/| |_| | |_| | | | (_) | | | |___) | ";
echo "\/     \__, |\__|_| |_|\___/|_| |_|____/  ";
echo "       |___/                              ";

RESET='\033[0m'
COLOR='\033[1;32m'

msg() {
  echo -e "${COLOR}$(date): $1${RESET}"
}

install_python35() {
    msg "Installing Python3.5 Packages"
    sudo apt update -qq
    sudo apt install -y \
                python3 \
                python3-dev \
                python3-tk \
                libpython3-dev \
                libpython3-stdlib \
                python3-setuptools \
                python3-numpy \
                python3-pip

    export PYTHONPATH=$HOME/.local/lib/python3.5/site-packages
    echo "export PYTHONPATH=/home/ubuntu/.local/lib/python3.5/site-packages" | tee -a /home/ubuntu/.bashrc
    echo "export PYTHONPATH=/home/ubuntu/.local/lib/python3.5/site-packages" | tee -a /home/ubuntu/.profile

    export PYTHON_BIN_PATH=/usr/bin/python3
    echo "export PYTHON_BIN_PATH=/usr/bin/python3" | tee -a /home/ubuntu/.bashrc
    echo "export PYTHON_BIN_PATH=/usr/bin/python3" | tee -a /home/ubuntu/.profile

    export PYTHON_LIB_PATH=$HOME/.local/lib/python3.5/site-packages
    echo "export PYTHON_LIB_PATH=/home/ubuntu/.local/lib/python3.5/site-packages" | tee -a /home/ubuntu/.bashrc
    echo "export PYTHON_LIB_PATH=/home/ubuntu/.local/lib/python3.5/site-packages" | tee -a /home/ubuntu/.profile
}

install_python36() {
    msg "Upgrading Python3"
    sudo add-apt-repository ppa:deadsnakes/ppa -y

    #Not official PPA
    sudo apt remove python3 python3.5 -y
    sudo apt purge --auto-remove python3 python3.5 -y

    sudo rm /usr/bin/python3.5 \
            /usr/bin/python3.5m \
            /usr/bin/python3 \
            /usr/bin/python3m

    sudo rm -rf /usr/lib/python3 \
                /usr/lib/python3.5 \
                /usr/local/lib/python3.5

    sudo ln -s /usr/bin/python3.6 /usr/bin/python3
    sudo ln -s /usr/bin/python3.6m /usr/bin/python3m

    msg "Installing Python3.6 Packages"
    sudo apt update -qq
    sudo apt install -y \
                python3.6 \
                python3.6-dev \
                python3.6-tk \
                libpython3.6 \
                libpython3.6-dev \
                libpython3.6-stdlib

    export PATH=/home/ubuntu/.local/bin:$PATH
    echo "export PATH=/home/ubuntu/.local/bin:$PATH" | tee -a /home/ubuntu/.bashrc
    echo "export PATH=/home/ubuntu/.local/bin:$PATH" | tee -a /home/ubuntu/.profile

    #curl -sL https://bootstrap.pypa.io/get-pip.py | bash -
    curl https://bootstrap.pypa.io/get-pip.py -o /home/ubuntu/get-pip.py
    chown ubuntu:ubuntu /home/ubuntu/get-pip.py
    python3 /home/ubuntu/get-pip.py --user
    rm /home/ubuntu/get-pip.py

    export PYTHONPATH=/home/ubuntu/.local/lib/python3.6/site-packages
    echo "export PYTHONPATH=/home/ubuntu/.local/lib/python3.6/site-packages" | tee -a /home/ubuntu/.bashrc
    echo "export PYTHONPATH=/home/ubuntu/.local/lib/python3.6/site-packages" | tee -a /home/ubuntu/.profile

    export PYTHON_BIN_PATH=/usr/bin/python3
    echo "export PYTHON_BIN_PATH=/usr/bin/python3" | tee -a /home/ubuntu/.bashrc
    echo "export PYTHON_BIN_PATH=/usr/bin/python3" | tee -a /home/ubuntu/.profile

    export PYTHON_LIB_PATH=/home/ubuntu/.local/lib/python3.6/site-packages
    echo "export PYTHON_LIB_PATH=/home/ubuntu/.local/lib/python3.6/site-packages" | tee -a /home/ubuntu/.bashrc
    echo "export PYTHON_LIB_PATH=/home/ubuntu/.local/lib/python3.6/site-packages" | tee -a /home/ubuntu/.profile
}

install_miniconda(){

  msg "Installing Miniconda"

  cd $HOME

  #From Host
  export ROOT_DIR=/opt/anaconda
  chmod +x /frameworks/anaconda/Miniconda3-latest-Linux-x86_64.sh
  sudo /frameworks/anaconda/Miniconda3-latest-Linux-x86_64.sh -b -p $ROOT_DIR
  sudo chown $USER:$USER $ROOT_DIR -R

  export PATH="$ROOT_DIR/bin:$PATH"
  echo "export PATH=$ROOT_DIR/bin:$PATH" | tee -a $HOME/.bashrc
  echo "export PATH=$ROOT_DIR/bin:$PATH" | tee -a $HOME/.profile

  #If your shell is Bash or a Bourne variant, enable conda for the current user with
  #echo ". /opt/anaconda/etc/profile.d/conda.sh" >> ~/.bashrc
  #or, for all users, enable conda with
  #sudo ln -s /opt/anaconda/etc/profile.d/conda.sh /etc/profile.d/conda.sh
  sudo ln -s /opt/anaconda/etc/profile.d/conda.sh /etc/profile.d/conda.sh

  msg "opt-out reporting errors"
  source activate
  conda config --set report_errors false
}

PARAM="3.5"
if [[ "$#" -gt 0 ]];then
    PARAM="$1"
fi

if [[ "$PARAM" == "3.5" ]];then
    install_python35;
elif [[ "$PARAM" == "3.6" ]];then
    install_python36;
elif [[ "$PARAM" == "miniconda" ]];then
    install_miniconda;
else 
  echo "Argument not found!"
  echo "Possible Values: (3.5, 3.6, anaconda, miniconda)."
fi